#!/usr/bin/env python3
"""Benchmark open-source reference gravity solvers on the SAME problem
02_nbody_gravity's `--bench` measures, so their cost/accuracy can be
overlaid on the ngrav sweep.

    nbody_bench_reference.py --ic-bin <dir-or-exe> --out ref.csv
        [--ns 1000,4000,16000] [--solvers fmm3d,pytreegrav]
        [--eps 1e-2,1e-3] [--theta 0.5,0.7] [--soft-eps 0.02]
        [--reps 0] [--label ref-node]

The problem: a Plummer sphere, seed 1, generated by `ngrav::ic::Plummer<3>`
and dumped via `02_nbody_gravity --dump-ic <file> --bench-n N` (raw float32
x,y,z,mass,vx,vy,vz per particle). Pass `--ic-bin` pointing at the built
`02_nbody_gravity[.exe]` and this script calls --dump-ic itself, or point it
at a directory of pre-dumped `ic_<N>.bin` files.

Reference solvers (install what you need; missing ones are skipped):
  fmm3d       -- FMM3D / fmm3dpy (Flatiron): Greengard-Gimbutas adaptive
                 spherical-harmonic Laplace FMM, Fortran+OpenMP. `--eps` is
                 its requested relative precision; recorded in the `theta`
                 column, `order` = -1. Kernel is bare 1/r; if `--soft-eps>0`
                 a KD-tree near-field correction makes it solve the exact
                 same Plummer-softened problem the ngrav bench does.
  pytreegrav  -- pytreegrav (Grudic): numba Barnes-Hut with native Plummer
                 softening and an opening-angle `--theta`. `order` = -1.

Output schema matches scripts/nbody_bench_sweep.sh:
  label,threads,solver,n,theta,order,ms_per_eval,mean_rel_err

mean_rel_err is the mean per-particle |a_ref - a_solver| / |a_ref| against a
chunked fp64 direct sum with the SAME softening -- the same metric the
ngrav bench uses.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time

import numpy as np

G = 1.0  # matches bench_ic::kG


# --------------------------------------------------------------------------
# problem: read (or generate) the exact Plummer sphere --bench uses
# --------------------------------------------------------------------------
def load_ic(ic_bin, n, workdir):
    """Return (pos[N,3] float64, mass[N] float64). `ic_bin` is either the
    built 02_nbody_gravity exe (we call --dump-ic) or a directory holding
    ic_<N>.bin."""
    if os.path.isdir(ic_bin):
        path = os.path.join(ic_bin, f"ic_{n}.bin")
        if not os.path.exists(path):
            sys.exit(f"reference: {path} not found (pre-dump it or pass the exe)")
    else:
        if not (os.path.isfile(ic_bin) and os.access(ic_bin, os.X_OK)):
            sys.exit(f"reference: --ic-bin '{ic_bin}' is neither a dir nor an executable")
        os.makedirs(workdir, exist_ok=True)
        path = os.path.join(workdir, f"ic_{n}.bin")
        r = subprocess.run([ic_bin, "--dump-ic", path, "--bench-n", str(n)],
                           capture_output=True, text=True)
        if r.returncode != 0 or not os.path.exists(path):
            sys.exit(f"reference: --dump-ic failed for N={n}\n{r.stderr}")
    rec = np.fromfile(path, dtype=np.float32).reshape(-1, 7).astype(np.float64)
    return np.ascontiguousarray(rec[:, :3]), np.ascontiguousarray(rec[:, 3])


# --------------------------------------------------------------------------
# fp64 direct reference (chunked, softened) -- the accuracy yardstick
# --------------------------------------------------------------------------
def direct_accel(pos, mass, soft_eps, chunk=2048):
    n = len(pos)
    a = np.zeros((n, 3))
    e2 = soft_eps * soft_eps
    for i0 in range(0, n, chunk):
        i1 = min(i0 + chunk, n)
        d = pos[None, :, :] - pos[i0:i1, None, :]           # (chunk, N, 3)
        r2 = np.einsum("ijk,ijk->ij", d, d) + e2
        for k in range(i0, i1):
            r2[k - i0, k] = np.inf                          # drop self term (inf -> 0 weight)
        inv = r2 ** -1.5
        a[i0:i1] = G * np.einsum("ij,j,ijk->ik", inv, mass, d)
    return a


def mean_rel_err(a_ref, a):
    num = np.linalg.norm(a - a_ref, axis=1)
    den = np.maximum(np.linalg.norm(a_ref, axis=1), 1e-30)
    return float(np.mean(num / den))


# --------------------------------------------------------------------------
# reference solvers
# --------------------------------------------------------------------------
def accel_fmm3d(pos, mass, eps, soft_eps):
    """FMM3D unsoftened 1/r accel; if soft_eps>0, add a KD-tree near-field
    correction so it matches the Plummer-softened problem exactly."""
    from fmm3dpy import lfmm3d  # noqa

    src = np.asfortranarray(pos.T)                       # (3, N)
    charges = np.asfortranarray(mass)
    # lfmm3d's kernel is 1/(4*pi*r); pg=2 -> potential + gradient AT the
    # sources. grad u = sum_j c_j (x_j - x) / (4 pi |x-x_j|^3) already points
    # toward the sources, i.e. the direction of gravitational attraction, so
    # a = G * sum_j m_j (x_j-x)/r^3 = 4*pi*G * out.grad  (verified vs direct
    # to ~8e-16). No sign flip.
    out = lfmm3d(eps=eps, sources=src, charges=charges, pg=2)
    a = (4.0 * np.pi * G) * np.ascontiguousarray(out.grad.T)   # (N, 3)

    if soft_eps > 0.0:
        # vectorised Plummer near-field correction: a_soft - a_unsoft is
        # sum_j m_j r_ij [(r^2+e^2)^-1.5 - r^-3], significant only for pairs
        # within a few softening lengths.
        from scipy.spatial import cKDTree
        e2 = soft_eps * soft_eps
        rc = 6.0 * soft_eps
        pairs = cKDTree(pos).query_pairs(rc, output_type="ndarray")   # (P, 2)
        if len(pairs):
            i, j = pairs[:, 0], pairs[:, 1]
            d = pos[j] - pos[i]                                       # (P, 3)
            r2 = np.einsum("pk,pk->p", d, d)
            corr = ((r2 + e2) ** -1.5 - r2 ** -1.5)[:, None] * d      # (P, 3)
            np.add.at(a, i, (G * mass[j])[:, None] * corr)
            np.add.at(a, j, -(G * mass[i])[:, None] * corr)
    return a


def accel_pytreegrav(pos, mass, theta, soft_eps):
    import pytreegrav  # noqa
    soft = np.full(len(pos), soft_eps)
    return pytreegrav.Accel(pos, mass, soft, theta=theta, G=G, method="tree")


# --------------------------------------------------------------------------
def timeit(fn, reps):
    fn()                       # warm
    t0 = time.perf_counter()
    for _ in range(reps):
        out = fn()
    dt = (time.perf_counter() - t0) / reps
    return out, dt * 1e3       # ms


def reps_for_n(n, forced):
    if forced > 0:
        return forced
    return 10 if n <= 8000 else 5 if n <= 64000 else 3


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ic-bin", required=True, help="built 02_nbody_gravity exe, or a dir of ic_<N>.bin")
    ap.add_argument("--out", required=True)
    ap.add_argument("--ns", default="1000,2000,4000,8000,16000,32000")
    ap.add_argument("--solvers", default="fmm3d,pytreegrav")
    ap.add_argument("--eps", default="1e-2,1e-3,1e-4", help="fmm3d requested precisions")
    ap.add_argument("--theta", default="0.5,0.7", help="pytreegrav opening angles")
    ap.add_argument("--soft-eps", type=float, default=0.0,
                    help="Plummer softening. 0 (default) = unsoftened 1/r, the clean regime for "
                         "comparing against FMM3D (whose kernel is 1/r); match the ngrav side with "
                         "--bench-eps 0 / a tiny value. >0 adds a KD-tree near-field correction, "
                         "which has its own ~1e-3 accuracy floor at a practical cutoff -- see the docstring.")
    ap.add_argument("--reps", type=int, default=0, help="0 = pick from N")
    ap.add_argument("--ref-max-n", type=int, default=60000, help="skip the O(N^2) accuracy check above this N")
    ap.add_argument("--label", default="")
    ap.add_argument("--workdir", default=None)
    args = ap.parse_args()

    ns = [int(x) for x in args.ns.split(",")]
    solvers = args.solvers.split(",")
    fmm_eps = [float(x) for x in args.eps.split(",")]
    thetas = [float(x) for x in args.theta.split(",")]
    workdir = args.workdir or os.path.join(os.path.dirname(os.path.abspath(args.out)), "_ref_ic")
    threads = os.environ.get("OMP_NUM_THREADS", "?")

    print(f"# platform={sys.platform}  OMP_NUM_THREADS={threads}  soft_eps={args.soft_eps}", file=sys.stderr)
    if sys.platform.startswith("win"):
        print("# WARNING: the fmm3dpy Windows wheel is often single-threaded / unoptimised --\n"
              "#   run this on Linux (Perlmutter: pip install fmm3d in the sweep job) for\n"
              "#   representative timing. Windows is fine for validating correctness.", file=sys.stderr)

    rows = []
    for n in ns:
        pos, mass = load_ic(args.ic_bin, n, workdir)
        a_ref = direct_accel(pos, mass, args.soft_eps) if n <= args.ref_max_n else None
        reps = reps_for_n(n, args.reps)
        print(f"=== N={n}  reps={reps}  ref={'yes' if a_ref is not None else 'skipped'} ===", file=sys.stderr)

        for solver in solvers:
            if solver == "fmm3d":
                try:
                    import fmm3dpy  # noqa
                except ImportError:
                    print("  fmm3d: fmm3dpy not installed -- skipping", file=sys.stderr)
                    continue
                for eps in fmm_eps:
                    try:
                        a, ms = timeit(lambda: accel_fmm3d(pos, mass, eps, args.soft_eps), reps)
                    except Exception as e:  # noqa
                        print(f"  fmm3d eps={eps}: {e}", file=sys.stderr)
                        continue
                    err = mean_rel_err(a_ref, a) if a_ref is not None else -1.0
                    rows.append((args.label, threads, "fmm3d", n, eps, -1, ms, err))
                    print(f"  fmm3d    eps={eps:<7} {ms:10.3f} ms   err={err:.3e}", file=sys.stderr)

            elif solver == "pytreegrav":
                try:
                    import pytreegrav  # noqa
                except ImportError:
                    print("  pytreegrav: not installed -- skipping", file=sys.stderr)
                    continue
                for th in thetas:
                    try:
                        a, ms = timeit(lambda: accel_pytreegrav(pos, mass, th, args.soft_eps), reps)
                    except Exception as e:  # noqa
                        print(f"  pytreegrav theta={th}: {e}", file=sys.stderr)
                        continue
                    err = mean_rel_err(a_ref, a) if a_ref is not None else -1.0
                    rows.append((args.label, threads, "pytreegrav", n, th, -1, ms, err))
                    print(f"  pytree   theta={th:<5} {ms:10.3f} ms   err={err:.3e}", file=sys.stderr)
            else:
                print(f"  unknown solver '{solver}' -- skipping", file=sys.stderr)

    with open(args.out, "w") as f:
        f.write("label,threads,solver,n,theta,order,ms_per_eval,mean_rel_err\n")
        for r in rows:
            f.write("{},{},{},{},{:.6g},{},{:.4f},{:.6e}\n".format(*r))
    print(f"wrote {args.out} ({len(rows)} rows)", file=sys.stderr)


if __name__ == "__main__":
    main()
